--- #YAML:1.0
name: Test-Number-Delta
version: 0.12
author:
  - David A Golden <dagolden@cpan.org>
abstract: |-
  Compare if the difference between two numbers 
  is within a specified precision
license: perl
requires:
  Test::Builder: 0.22
  perl: 5.004
build_requires:
  Test::Builder::Tester: 1.01
  Test::More: 0.54
provides:
  Test::Number::Delta:
    file: lib/Test/Number/Delta.pm
    version: 0.12
generated_by: Module::Build version 0.2606
