---
name: Test-Number-Delta
version: 1.03
author:
  - 'David A. Golden <dagolden@cpan.org>'
abstract: Compare the difference between numbers against a given tolerance
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Test::Builder: 0.32
  Test::Builder::Tester: 1.02
  Test::More: 0.45
  perl: 5.004
provides:
  Test::Number::Delta:
    file: lib/Test/Number/Delta.pm
    version: 1.03
generated_by: Module::Build version 0.2805
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
