--- #YAML:1.0
name: Test-Number-Delta
version: 0.11
author:
  - david@dagolden.com
abstract: |-
  Compare if the difference between two numbers 
  is within a specified precision
license: perl
requires:
  Test::Builder: 0.22
build_requires:
  Test::Builder::Tester: 1.01
  Test::More: 0.53
provides:
  Test::Number::Delta:
    file: lib/Test/Number/Delta.pm
    version: 0.11
generated_by: Module::Build version 0.2606
