---
name: Test-Number-Delta
version: 0.16
author:
  - David A Golden <dagolden@cpan.org>
abstract: |-
  Compare if the difference between two numbers 
  is within a specified amount
license: perl
requires:
  Test::Builder: 0.3
  perl: 5.004
build_requires:
  Test::Builder::Tester: 1.01
  Test::Exception: 0.2
  Test::More: 0.47
provides:
  Test::Number::Delta:
    file: lib/Test/Number/Delta.pm
    version: 0.16
generated_by: Module::Build version 0.2701
